import Init
import Init.Data.Order.Classes

/-!
# Published Theorem 15: semantic basis poset

Source: Causal Foundations v1.0, section 12.2, page 22.
DOI: 10.5281/zenodo.22902457.

The library has exactly m declared atoms, indexed by Fin m. A basis is a
subset of those indices. Truth, entailment and equivalence are evaluated only
inside the supplied ambient class. The actual semantic quotient carries a
weak-to-strong partial order. Domain maximality compares only conjunctions
generated by this same fixed library, including the empty conjunction.
-/

namespace CausalFoundations.Semantic

universe u

abbrev Basis (m : Nat) := Fin m → Prop

def Holds {m : Nat} {Model : Type u} (h : Fin m → Model → Prop)
    (S : Basis m) (x : Model) : Prop := ∀ i, S i → h i x

def Domain {m : Nat} {Model : Type u} (A : Model → Prop)
    (h : Fin m → Model → Prop) (S : Basis m) (x : Model) : Prop :=
  A x ∧ Holds h S x

def Included {Model : Type u} (D E : Model → Prop) : Prop := ∀ x, D x → E x

def SemanticEq {m : Nat} {Model : Type u} (A : Model → Prop)
    (h : Fin m → Model → Prop) (S T : Basis m) : Prop :=
  ∀ x, A x → (Holds h S x ↔ Holds h T x)

theorem domain_empty {m : Nat} {Model : Type u} (A : Model → Prop)
    (h : Fin m → Model → Prop) (x : Model) :
    Domain A h (fun _ => False) x ↔ A x := by
  constructor
  · exact And.left
  · intro ha
    exact ⟨ha, fun _ hi => False.elim hi⟩

theorem semantic_eq_refl {m : Nat} {Model : Type u} (A : Model → Prop)
    (h : Fin m → Model → Prop) (S : Basis m) : SemanticEq A h S S :=
  fun _ _ => Iff.rfl

theorem semantic_eq_symm {m : Nat} {Model : Type u} (A : Model → Prop)
    (h : Fin m → Model → Prop) {S T : Basis m}
    (he : SemanticEq A h S T) : SemanticEq A h T S :=
  fun x ha => (he x ha).symm

theorem semantic_eq_trans {m : Nat} {Model : Type u} (A : Model → Prop)
    (h : Fin m → Model → Prop) {S T U : Basis m}
    (he : SemanticEq A h S T) (hf : SemanticEq A h T U) :
    SemanticEq A h S U := fun x ha => (he x ha).trans (hf x ha)

theorem semantic_eq_iff_domains {m : Nat} {Model : Type u} (A : Model → Prop)
    (h : Fin m → Model → Prop) (S T : Basis m) :
    SemanticEq A h S T ↔ (∀ x, Domain A h S x ↔ Domain A h T x) := by
  constructor
  · intro he x
    constructor
    · intro hs
      exact ⟨hs.1, (he x hs.1).mp hs.2⟩
    · intro ht
      exact ⟨ht.1, (he x ht.1).mpr ht.2⟩
  · intro he x ha
    exact ⟨fun hs => ((he x).mp ⟨ha, hs⟩).2,
           fun ht => ((he x).mpr ⟨ha, ht⟩).2⟩

theorem semantic_eq_iff_domain_equal {m : Nat} {Model : Type u} (A : Model → Prop)
    (h : Fin m → Model → Prop) (S T : Basis m) :
    SemanticEq A h S T ↔ Domain A h S = Domain A h T := by
  constructor
  · intro he
    exact funext (fun x => propext ((semantic_eq_iff_domains A h S T).mp he x))
  · intro he
    apply (semantic_eq_iff_domains A h S T).mpr
    intro x
    rw [he]

def basisSetoid {m : Nat} {Model : Type u} (A : Model → Prop)
    (h : Fin m → Model → Prop) : Setoid (Basis m) where
  r := SemanticEq A h
  iseqv := ⟨semantic_eq_refl A h, semantic_eq_symm A h, semantic_eq_trans A h⟩

abbrev SemanticBasis {m : Nat} {Model : Type u} (A : Model → Prop)
    (h : Fin m → Model → Prop) := Quotient (basisSetoid A h)

def classOf {m : Nat} {Model : Type u} (A : Model → Prop)
    (h : Fin m → Model → Prop) (S : Basis m) : SemanticBasis A h :=
  Quotient.mk (basisSetoid A h) S

def classDomain {m : Nat} {Model : Type u} (A : Model → Prop)
    (h : Fin m → Model → Prop) : SemanticBasis A h → Model → Prop :=
  Quotient.lift (Domain A h)
    (fun S T he => (semantic_eq_iff_domain_equal A h S T).mp he)

theorem domain_classOf {m : Nat} {Model : Type u} (A : Model → Prop)
    (h : Fin m → Model → Prop) (S : Basis m) :
    classDomain A h (classOf A h S) = Domain A h S := rfl

theorem classOf_eq_iff {m : Nat} {Model : Type u} (A : Model → Prop)
    (h : Fin m → Model → Prop) (S T : Basis m) :
    classOf A h S = classOf A h T ↔ SemanticEq A h S T :=
  ⟨fun he => Quotient.exact he,
   fun he => Quotient.sound (s := basisSetoid A h) he⟩

theorem class_domain_injective {m : Nat} {Model : Type u} (A : Model → Prop)
    (h : Fin m → Model → Prop) (q r : SemanticBasis A h)
    (he : classDomain A h q = classDomain A h r) : q = r := by
  revert he
  refine Quotient.inductionOn₂ q r (fun S T he => ?_)
  exact Quotient.sound ((semantic_eq_iff_domain_equal A h S T).mpr he)

instance basisLE {m : Nat} {Model : Type u} (A : Model → Prop)
    (h : Fin m → Model → Prop) : LE (SemanticBasis A h) where
  le q r := Included (classDomain A h r) (classDomain A h q)

theorem class_le_refl {m : Nat} {Model : Type u} (A : Model → Prop)
    (h : Fin m → Model → Prop) (q : SemanticBasis A h) : q ≤ q :=
  fun _ hx => hx

theorem class_le_trans {m : Nat} {Model : Type u} (A : Model → Prop)
    (h : Fin m → Model → Prop) {q r s : SemanticBasis A h}
    (hqr : q ≤ r) (hrs : r ≤ s) : q ≤ s := fun x hx => hqr x (hrs x hx)

theorem class_le_antisymm {m : Nat} {Model : Type u} (A : Model → Prop)
    (h : Fin m → Model → Prop) {q r : SemanticBasis A h}
    (hqr : q ≤ r) (hrq : r ≤ q) : q = r := by
  apply class_domain_injective A h q r
  exact funext (fun x => propext ⟨hrq x, hqr x⟩)

instance basisPartialOrder {m : Nat} {Model : Type u} (A : Model → Prop)
    (h : Fin m → Model → Prop) : Std.IsPartialOrder (SemanticBasis A h) where
  le_refl := class_le_refl A h
  le_trans := fun _ _ _ => class_le_trans A h
  le_antisymm := fun _ _ => class_le_antisymm A h

theorem class_order_iff {m : Nat} {Model : Type u} (A : Model → Prop)
    (h : Fin m → Model → Prop) (S T : Basis m) :
    classOf A h S ≤ classOf A h T ↔ Included (Domain A h T) (Domain A h S) := Iff.rfl

theorem class_order_entailment {m : Nat} {Model : Type u} (A : Model → Prop)
    (h : Fin m → Model → Prop) (S T : Basis m) :
    classOf A h S ≤ classOf A h T ↔
      (∀ x, A x → Holds h T x → Holds h S x) := by
  constructor
  · intro he x ha ht
    exact (he x ⟨ha, ht⟩).2
  · intro he x ht
    exact ⟨ht.1, he x ht.1 ht.2⟩

theorem basis_subset_implies_order {m : Nat} {Model : Type u} (A : Model → Prop)
    (h : Fin m → Model → Prop) {S T : Basis m} (hst : ∀ i, S i → T i) :
    classOf A h S ≤ classOf A h T :=
  fun _ hx => ⟨hx.1, fun i hi => hx.2 i (hst i hi)⟩

def Sufficient {m : Nat} {Model : Type u} (A : Model → Prop)
    (h : Fin m → Model → Prop) (C : Model → Prop) (S : Basis m) : Prop :=
  Included (Domain A h S) C

def ClassSufficient {m : Nat} {Model : Type u} (A : Model → Prop)
    (h : Fin m → Model → Prop) (C : Model → Prop) (q : SemanticBasis A h) : Prop :=
  Included (classDomain A h q) C

theorem sufficient_equiv {m : Nat} {Model : Type u} (A : Model → Prop)
    (h : Fin m → Model → Prop) (C : Model → Prop) {S T : Basis m}
    (he : SemanticEq A h S T) : Sufficient A h C S ↔ Sufficient A h C T := by
  constructor
  · intro hs x hx
    exact hs x ((semantic_eq_iff_domains A h S T).mp he x |>.mpr hx)
  · intro ht x hx
    exact ht x ((semantic_eq_iff_domains A h S T).mp he x |>.mp hx)

theorem class_sufficient_iff {m : Nat} {Model : Type u} (A : Model → Prop)
    (h : Fin m → Model → Prop) (C : Model → Prop) (S : Basis m) :
    ClassSufficient A h C (classOf A h S) ↔ Sufficient A h C S := Iff.rfl

theorem sufficient_upper {m : Nat} {Model : Type u} (A : Model → Prop)
    (h : Fin m → Model → Prop) (C : Model → Prop) {q r : SemanticBasis A h}
    (hq : ClassSufficient A h C q) (hqr : q ≤ r) : ClassSufficient A h C r :=
  fun x hx => hq x (hqr x hx)

abbrev SufficientClass {m : Nat} {Model : Type u} (A : Model → Prop)
    (h : Fin m → Model → Prop) (C : Model → Prop) :=
  {q : SemanticBasis A h // ClassSufficient A h C q}

instance sufficientLE {m : Nat} {Model : Type u} (A : Model → Prop)
    (h : Fin m → Model → Prop) (C : Model → Prop) : LE (SufficientClass A h C) where
  le q r := q.val ≤ r.val

theorem sufficient_le_refl {m : Nat} {Model : Type u} (A : Model → Prop)
    (h : Fin m → Model → Prop) (C : Model → Prop) (q : SufficientClass A h C) : q ≤ q :=
  class_le_refl A h q.val

theorem sufficient_le_trans {m : Nat} {Model : Type u} (A : Model → Prop)
    (h : Fin m → Model → Prop) (C : Model → Prop) {q r s : SufficientClass A h C}
    (hqr : q ≤ r) (hrs : r ≤ s) : q ≤ s := class_le_trans A h hqr hrs

theorem sufficient_le_antisymm {m : Nat} {Model : Type u} (A : Model → Prop)
    (h : Fin m → Model → Prop) (C : Model → Prop) {q r : SufficientClass A h C}
    (hqr : q ≤ r) (hrq : r ≤ q) : q = r :=
  Subtype.eq (class_le_antisymm A h hqr hrq)

instance sufficientPartialOrder {m : Nat} {Model : Type u} (A : Model → Prop)
    (h : Fin m → Model → Prop) (C : Model → Prop) :
    Std.IsPartialOrder (SufficientClass A h C) where
  le_refl := sufficient_le_refl A h C
  le_trans := fun _ _ _ => sufficient_le_trans A h C
  le_antisymm := fun _ _ => sufficient_le_antisymm A h C

def MinimalSufficient {m : Nat} {Model : Type u} (A : Model → Prop)
    (h : Fin m → Model → Prop) (C : Model → Prop) (q : SemanticBasis A h) : Prop :=
  ClassSufficient A h C q ∧ ∀ r, ClassSufficient A h C r → r ≤ q → r = q

def MaximalSufficientDomain {m : Nat} {Model : Type u} (A : Model → Prop)
    (h : Fin m → Model → Prop) (C : Model → Prop) (S : Basis m) : Prop :=
  Sufficient A h C S ∧ ∀ T, Sufficient A h C T →
    Included (Domain A h S) (Domain A h T) → Included (Domain A h T) (Domain A h S)

theorem minimal_iff_maximal_domain {m : Nat} {Model : Type u} (A : Model → Prop)
    (h : Fin m → Model → Prop) (C : Model → Prop) (S : Basis m) :
    MinimalSufficient A h C (classOf A h S) ↔ MaximalSufficientDomain A h C S := by
  constructor
  · intro hm
    refine ⟨hm.1, fun T ht hst => ?_⟩
    have he := hm.2 (classOf A h T) ht hst
    have hle : classOf A h S ≤ classOf A h T := by
      rw [he]
      exact class_le_refl A h (classOf A h S)
    exact hle
  · intro hd
    refine ⟨hd.1, ?_⟩
    intro r
    refine Quotient.inductionOn r (fun T ht hts => ?_)
    exact class_le_antisymm A h hts (hd.2 T ht hts)

end CausalFoundations.Semantic

namespace CausalFoundations

open Semantic

/-- Every asserted part of the published finite-library semantic basis theorem. -/
theorem theorem15 {m : Nat} {Model : Type u} (A : Model → Prop)
    (h : Fin m → Model → Prop) (C : Model → Prop) :
    (∀ q : SufficientClass A h C, q ≤ q) ∧
    (∀ q r s : SufficientClass A h C, q ≤ r → r ≤ s → q ≤ s) ∧
    (∀ q r : SufficientClass A h C, q ≤ r → r ≤ q → q = r) ∧
    (∀ q r : SemanticBasis A h, ClassSufficient A h C q → q ≤ r →
      ClassSufficient A h C r) ∧
    (∀ S T, classOf A h S ≤ classOf A h T ↔
      Included (Domain A h T) (Domain A h S)) ∧
    (∀ S, MinimalSufficient A h C (classOf A h S) ↔
      MaximalSufficientDomain A h C S) :=
  ⟨sufficient_le_refl A h C,
   fun _ _ _ => sufficient_le_trans A h C,
   fun _ _ => sufficient_le_antisymm A h C,
   fun _ _ => sufficient_upper A h C,
   class_order_iff A h,
   minimal_iff_maximal_domain A h C⟩

end CausalFoundations
